### ISSUE TITLE
These are some Arabic language files,

### ISSUE THREAD

**Issue by eArabic** [zlaxy/aeiou#1]
Hello dear friend
Sorry for the delay, these are some files.
 I will be collecting others later.
 https://www.upload.ee/files/7650327/Photo_Sound.zip.html
https://www.upload.ee/files/7650340/Learn_Arabic.zip.html
https://www.upload.ee/files/7650341/photo.zip.html

**Comment by zlaxy** [comment]
Hello, friend. Many thanks for your help. We need some time for sorting this files for our project...
Also, you could check: https://oss-it.ru/share/aeiou/ - there is English, Russian, Greek and Rune sounds already. Hope, we'll add Arabic sounds soon.

**Comment by zlaxy** [comment]
@eArabic hello, friend!
Finally we added the Arabic abjad to this program, please test and check it:
https://oss-it.ru/share/aeiou/
(while there is no alignment, but i plan to solve this problem soon)

**Comment by eArabic** [comment]
Hello dear friend
Thank you very much, Excellent work Excellent, you all thanks and respect.
I am happy with this excellent result, there is a mistake in the word **hello** and this is correct:
 مرحبا  = دجبا

<span style="font-family: 'Mirza', cursive;">مرحبا</span>

![99](https://user-images.githubusercontent.com/24383546/39374727-7a8aab3a-4a54-11e8-92b6-5876ccccd3aa.png)

**Comment by zlaxy** [comment]
@eArabic Ah, but there is not word, it's just first letters (like ABCD).
So do not write in Arabic? Maybe more correct will be:
أبجدي
?

**Comment by eArabic** [comment]
Hello dear friend
Sorry I did not pay attention to it, I think the word: Hello Arabic
Well done right, now I understand, the best thing to write: Abjad = أبجد

**Comment by eArabic** [comment]
<span style="font-family: 'Mirza', cursive;">أبجد</span>

`<span style="font-family: 'Mirza', cursive;">أبجد</span>`




![4](https://user-images.githubusercontent.com/24383546/39422980-8b8f7782-4c78-11e8-850c-f31903a6884c.png)
 
https://en.wikipedia.org/wiki/Arabic_alphabet
https://en.wikipedia.org/wiki/Abjad

**Comment by zlaxy** [comment]
@eArabic thanks!
https://github.com/zlaxy/aeiou/commit/614a4941e9027037fa703894a4fd893034be8945

**Comment by aeioubt** [comment]
Now it's اجبد instead of ابجد

**Comment by zlaxy** [comment]
@aeioubt there https://oss-it.ru/share/aeiou/ - now `أبجد`
