### ISSUE TITLE
нѣмецкія слова

### ISSUE THREAD

**Issue by Socialdarwinist** [zlaxy/aeiou#10]
[aeiou-deutsch.ods.zip](https://github.com/zlaxy/aeiou/files/1636972/aeiou-deutsch.ods.zip)

Я въ таблицѣ собралъ нѣмецкія слова съ переводомъ на русскій и англійскій, чтобы представлялась каждая фонема хорошо.

**Comment by aeioubt** [comment]
Извините, можете сдѣлать то же самое, но используя какъ можно болѣе ​базовыя​, ​простыя​ слова. Вродѣ ich, du, bist, bauw, baum etc. Желательно не больше 5 буквъ на слово. Можно ограничиться лишь спискомъ словъ (безъ транскрипціи и перевода) и можно на каждое слово использовать нѣсколько словъ, а можно и по одному слову на каждый примѣръ какъ здѣсь сдѣлано оставить. Можно даже просто сюда ихъ въ тѣло комментарія помѣстить.
Спасибо.

**Comment by zlaxy** [comment]
https://github.com/zlaxy/aeiou/commit/ef6891c97d2c001351c90a300ec5a252e4a93d31
