### ISSUE TITLE
left letters at iphones

### ISSUE THREAD

**Issue by aeioubt** [zlaxy/aeiou#11]
![photo1](https://user-images.githubusercontent.com/19191381/35997632-1e72ab06-0d2b-11e8-8086-d359a0e1992e.jpg)

**Comment by zlaxy** [comment]
done: 2c5fe5aba45d1fc590b9172d95aeb296219363ed

**Comment by zlaxy** [comment]
https://zlaxy.github.io/aeiou/ - there you could test
