### ISSUE TITLE
to reprogram colouring

### ISSUE THREAD

**Issue by aeioubt** [zlaxy/aeiou#12]
Arabic alphabet's shown that we need to colour letters as we put them in one tag, so maybe they will merge in one word according to arabic orthography. Thus we have to switch off the colouring which goes afterwards and I will refill all the tags for other alphabets, if we have to make all the alphabets in the same pattern.

**Comment by zlaxy** [comment]
https://github.com/zlaxy/aeiou/commit/12d7d21a78962d81597bd73713132a69ba3472e3

Теперь можно задавать расцветку стандартными средствами html, для этого в соответствующем Sound Correspondence нужно задать тэг span, например:
`tableAbcd["english"]["sound"]["j"] = [ "j", " ", "<span style=\"color:red\">o</span><span style=\"color:blue\">y</span>", "" ];`
