### ISSUE TITLE
english cursive

### ISSUE THREAD

**Issue by aeioubt** [zlaxy/aeiou#3]
Английский маюскул курсив:
A - все
1B - 2,3 слова
дальше просто буду перечислять в которых:
Е
G - bright (в обычном латинском такая же ошибка, и вообще как-то эти ошибки в других представлениях иногда повторяются)
I
L
M - чуть-чуть правее надо
N - чуть-чуть правее надо
О - чуть-чуть поправить
R - может в arc а чуть поближе
U - чуть правее
V - в love lo чуть правее
W
X - e in ex a little to the right
Y
Z

**Comment by aeioubt** [comment]
Не могу отредактировать комментарий: жму на карандаш - говорит эдит коммент и ничего

Это замечания к положению букв: сейчас пишет  br   Ight или налазит одна буква на другую

**Comment by zlaxy** [comment]
Странно, а я могу твои комментарии редактировать. Может в браузере дело?

Понял про буквы...подумаю как сделать, наверно отдельную разметку под курсивные алфавиты придется делать.

**Comment by zlaxy** [comment]
Please check this out again. If everything is fine - i'll close this issue.

**Comment by aeioubt** [comment]
Если вопрос про редактирование комментов на гитхабе, то под файрфоксом всё
работает.
Но скорей всего вопрос был про английский курсив, раз вижу что починил
многое,
осталось несколько косячков:
в печатных буквах
la B (в курсиве lab нормально, а в следующем слове lam наезжает на B)
hom E (а в курсиве наоборот hom наезжает на Е)
lo Ve (в курсиве норм)
jo Y (в курсиве норм)
ver Y (в курсиве ver наоборот наезжает на Y)
var Y (в курсиве var наоборот наезжает на Y)
в курсиве также whY c наездом
в остальном курсив прекрасен, за исключением того, что там непрозрачный фон
особенно необходим, потому что при наложении на соседние буквы текст
становится нечиитаем: например, Xenos
в строчном курсиве можно было бы пододвинуть остальные буквы к основной, но
видишь не умею читать код, потому даже приблизительно не представляю какие
трудности это может вызывать (скорей всего ты одинаковый код делал и для
прописных и для строчных, это конечно неправильно, они разной ширины)

И ещё вопрос: почему оно такое маленькое? Давай его во весь экран сделаем,
а то особенно на телефоне странно выглядит (на компе норм, но на нём и
большое будет неплохо)
даёшь 250% масштаба!

**Comment by zlaxy** [comment]
> даёшь 250% масштаба!

посмотри как сейчас. масштаб формируется по высоте экрана (можно еще по ширине попробовать, или еще как).  так устроит? только имею ввиду размер самих букв на экране а не всплывающих произношений.
если да - если устраивает - переделаю всплывающие произношения слов соответствующим образом

**Comment by aeioubt** [comment]
Размер в браузере гораздо лучше (но слова теперь загораживают букву, нужно
бы как-то эти размеры чтоб от размера шрифта зависили (тогда и рукописный с
печатным связаны не будут)
На айфонище когда его держишь горизонтально более-менее, а когда
вертикально - не все буквы буквы влазят в экран, а сузить изображение не
получается.

2018-01-08 23:52 GMT+05:00 ivan <notifications@github.com>:

**Comment by zlaxy** [comment]
> На айфонище когда его держишь горизонтально более-менее, а когда вертикально - не все буквы буквы влазят в экран, а сузить изображение не получается.

А так? (рекомендую предварительно открыть в браузере еще файл https://oss-it.ru/share/aeiou/aeiou.css - и в нём F5)

И да, на личные темы лучше здесь не общаться. Для этого лучше использовать почту/xmpp.

**Comment by zlaxy** [comment]
Переделал принцип расположения всплывающих надписей в https://github.com/zlaxy/aeiou/commit/a376341cc2ba213c4a88bbd7222e06e6e2743282
Теперь расстояние букв слева и справа высчитывается индивидуально для каждой буквы. Только транскрипция снизу может кривовато пока выставляется, но в принципе ее тоже можно сделать симметричной.
Если такой вариант устраивает - думаю эту тему можно прикрывать.
