### ISSUE TITLE
to indicate if alphabet has sound or it doesn't

### ISSUE THREAD

**Issue by aeioubt** [zlaxy/aeiou#6]
Please, make names of alphabets, which don't have sound, on the right side in grey colour. 
Пожалуйста, сделай имена алфавитов, что не озвучены, справа серым светом, чтоб человек не бросал втыкать после того как случайно наткнулся на пару неозвученных.

**Comment by zlaxy** [comment]
https://github.com/zlaxy/aeiou/commit/839275f8082c953465f955499595427db0f7f120
