### ISSUE TITLE
использование клавиатуры

### ISSUE THREAD

**Issue by aeioubt** [zlaxy/aeiou#8]
Можно ли сделать чтоб экран менялся при помощи стрелок? верх-вниз чтоб меняло алфавит (сначала в группе (русский-болгарский) а после по группам (грузинский, еврейский) - а влево-право чтоб меняло прописные-строчные-печатные-курсивные

**Comment by aeioubt** [comment]
а пробел чтоб менял линейную-осевую (там где осевая есть) и может скоро добавим третье представление для некоторых, 
правая кнопка мышки бы чтоб играла не следующий а этот же, двойной щелчок правой клавиши проматывал бы на одно слово в обратную сторону.
На клавиатуре чтоб буквы можно было нажимать тоже можно сделать, но это может наверное систему грохнуть если все кнопки кто-то сразу нажмёт и столько аудиофайлов сразу запустится. или нет?

**Comment by zlaxy** [comment]
Сделал кнопки:
https://github.com/zlaxy/aeiou/commit/00b1c47b0c3bced3a2106c4c9108f3c081d3a1fc

https://developer.mozilla.org/ru/docs/Web/API/GlobalEventHandlers/onkeypress
> Браузеры на основе Webkit (к примеру, Google Chrome и Safari) не отрабатывают события нажатия клавиш-указателей ("стрелок").
> Firefox не отрабатывает события, в основе которых лежат клавиши управления (модификаторы) - такие, как, например, SHIFT.

Поэтому для Webkit сделал WASD - это стандратный аналог стрелок на клавиатуре.
Идея нажимать буквы на клавиатуре и слышать их - на мой взгялд неудачная, так как будет работать только с английским-немецким. Для остальных языков нужно подгружать экранную клавиатуру или заказывать наклейки на клавиатуру чтоб знать где какая буква.

Про события кнопок мышки рекомендую хорошенько подумать или посмотреть как обычно обрабатываются левые,правые,средние щелчки мыши - и делать отдельный issue по событиям мыши. Конкретно здесь предложенный тобой вариант, на мой взгляд, не стоит реализовывать. События "двойной щелчок правой кнопкой мыши" вообще нигде не встречал на практике, надо делать простой, интуитивно понятный интерфейс, чтобы не требовалось никаких инструкций и пояснений.

Этот вопрос насчет клавиатуры закрываю.
