### ISSUE TITLE
непрозрачный фон

### ISSUE THREAD

**Issue by aeioubt** [zlaxy/aeiou#9]
![chip](https://user-images.githubusercontent.com/19191381/34943237-a847f3a8-fa1c-11e7-9307-fdabe67a596e.png)
Под словами нужно сделать фон непрозрачным.

**Comment by aeioubt** [comment]
добавил изображение (из-под файрфокса, хром на гитхабе реально хром)

**Comment by zlaxy** [comment]
Добавил тени к вспылвающим серым буквам.
